<?php

namespace App\Services\User;

use Illuminate\Support\Facades\Hash;
use LaravelEasyRepository\Service;
use App\Repositories\User\UserRepository;

class UserServiceImplement extends Service implements UserService{

     /**
     * don't change $this->mainRepository variable name
     * because used in extends service class
     */
     protected $mainRepository;

    public function __construct(UserRepository $mainRepository)
    {
      $this->mainRepository = $mainRepository;
    }

    public function create($data)
    {
        $data['password'] = Hash::make($data['password']);
        return parent::create($data); // TODO: Change the autogenerated stub
    }

//    public function update($id, array $data)
//    {
//        $update = [
//            'name' => $data['name'],
////            'birthday' => date("Y-m-d", strtotime($data['birthday'])),
//            'birthday' => $data['birthday'],
//            'occupation' => $data['occupation'],
//        ];
//
//        if (auth()->user()->email !== $data['email']){
//            $update['email'] = $data['email'];
//        }
//
//        if (auth()->user()->username !== $data['username']){
//            $update['username'] = $data['username'];
//        }
//        return parent::update($id, $update); // TODO: Change the autogenerated stub
//    }
}
