<?php

namespace App\Services\BookCategory;

use App\Repositories\Book\BookRepository;
use LaravelEasyRepository\Service;
use App\Repositories\BookCategory\BookCategoryRepository;

class BookCategoryServiceImplement extends Service implements BookCategoryService{

     /**
     * don't change $this->mainRepository variable name
     * because used in extends service class
     */
     protected $mainRepository;
    public function __construct(BookCategoryRepository $mainRepository)
    {
      $this->mainRepository = $mainRepository;
    }

    public function create($data)
    {
        if (auth()->user()->is_admin != 1) {
            return redirect()->back()->with("failed", "You are not the author.");
        }
        $data['category_name'] = str($data['category_name'])->title();

        return parent::create($data); // TODO: Change the autogenerated stub
    }

    // Define your custom methods :)
    public function delete($id)
    {
        if (auth()->user()->is_admin != 1) {
            return redirect()->back()->with("failed", "You are not the author.");
        }
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
